"""
Django settings for Road24_Bot project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os

# -------------------------
#       BASE DIR
# -------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------
#       SECRET KEY & DEBUG
# -------------------------
SECRET_KEY = "django-insecure-3%cw@dg@owp)oxdxx)5)-(r(a*az*by9-dra9c2%yo_s^o66dr"
DEBUG = True

ALLOWED_HOSTS = ["*", "127.0.0.1", "localhost"]

# -------------------------
#       INSTALLED APPS
# -------------------------
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bot',  # Telegram bot app
]

# -------------------------
#       MIDDLEWARE
# -------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Road24_Bot.urls'



JAZZMIN_SETTINGS = {
    "site_title": "Road24 Bot",
    "site_header": "🚗 Road24 Bot Admin",
    "site_brand": "Road24",
    "site_logo": None,
    "welcome_sign": "Road24 Bot boshqaruv paneli",
    "copyright": "Road24",

    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "Foydalanuvchilar", "url": "admin:bot_telegramuser_changelist"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "bot.telegramuser": "fas fa-robot",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "site_title": "Road24 Admin",
    "site_header": "Road24",
    "site_brand": "Road24",
    "welcome_sign": "Road24 Admin Panel",

    "site_logo_classes": "img-circle",

    "copyright": "Road24",

    # yuqori menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"model": "auth.User"},
    ],

    # sidebar menyu
    "show_sidebar": True,
    "navigation_expanded": True,

    # ICON lar
    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "bot.telegramuser": "fab fa-telegram",
    },

    # oq tema
    "theme": "flatly",

    # dark modeni o'chirish
    "dark_mode_theme": None,

    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",        # ← DARK TEMA
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# -------------------------
#       TEMPLATES
# -------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Road24_Bot.wsgi.application'

# -------------------------
#       DATABASE
# -------------------------
DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "telegramuser",
            "USER": "postgres",
            "PASSWORD": "jasur1234",
            "HOST": "127.0.0.1",
            "PORT": "5432",
       }
    }

# -------------------------
#       PASSWORD VALIDATORS
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------
#       LOCALE SETTINGS
# -------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = False

# -------------------------
#       STATIC FILES
# -------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# -------------------------
#       DEFAULT PRIMARY KEY
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------
#       TELEGRAM BOT TOKEN
# -------------------------
TELEGRAM_BOT_TOKEN = "8433240326:AAH-H145wv2w_IU6TgnhQmAgTNnnZgyE_EU"

# -------------------------
#   DJANGO SETTINGS READY FOR SCRIPT
# -------------------------
# Agar botni Django context bilan mustaqil ishga tushirish kerak bo‘lsa:
if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Road24_Bot.settings")
    import django
    django.setup()


CSRF_TRUSTED_ORIGINS = ['https://rely-nonsubscribing-cari.ngrok-free.dev']