# Generated by Django 5.2.10 on 2026-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
