# Generated by Django 5.2.10 on 2026-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_last_seen_telegramuser_message_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek"), ('ru', 'Русский')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
