# Generated by Django 5.2.10 on 2026-03-26 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_buttonclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarimaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': '🚔 Jarima bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='MashinaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': '🚔 Mashina bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='MikroClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Mikroqarz',
                'verbose_name_plural': '🧰 Mikroqarz bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='OneIdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'ONE ID',
                'verbose_name_plural': '🛡 ONE ID bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'AutoSignal',
                'verbose_name_plural': '📡 AutoSignal bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='SlowClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Ilova ishlashi',
                'verbose_name_plural': '🐌 Ilova ishlashi bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': '📱 SMS bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='SugurtaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': "Sug'urta",
                'verbose_name_plural': "🛡 Sug'urta bosishlar",
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='TexClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': "Texnik ko'rik",
                'verbose_name_plural': "🧰 Texnik ko'rik bosishlar",
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='TonirovkaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Tonirovka',
                'verbose_name_plural': '🎨 Tonirovka bosishlar',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
