# Generated by Django 5.2.10 on 2026-03-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_jarimaclick_mashinaclick_mikroclick_oneidclick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_clicks', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Operator tugmasi',
                'verbose_name_plural': '👨\u200d💼 Operator bosilishi',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
