# Generated by Django 5.2.10 on 2026-03-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_operatorclick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mashinaclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'Mashina', 'verbose_name_plural': '🚗 Mashina bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='mikroclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'Mikroqarz', 'verbose_name_plural': '💰 Mikroqarz bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='oneidclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'ONE ID', 'verbose_name_plural': '♻️ ONE ID bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='operatorclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'Operator', 'verbose_name_plural': '👨\u200d💼 Operator bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='signalclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'AutoSignal', 'verbose_name_plural': '🚨 AutoSignal bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='slowclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'Ilova ishlashi', 'verbose_name_plural': '📲 Ilova ishlashi bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='smsclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'SMS', 'verbose_name_plural': '📨 SMS bosishlar'},
        ),
        migrations.AlterModelOptions(
            name='texclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': "Texnik ko'rik", 'verbose_name_plural': "🚧 Texnik ko'rik bosishlar"},
        ),
        migrations.AlterModelOptions(
            name='tonirovkaclick',
            options={'ordering': ['-clicked_at'], 'verbose_name': 'Tonirovka', 'verbose_name_plural': '🕶 Tonirovka bosishlar'},
        ),
        migrations.AddField(
            model_name='operatorclick',
            name='button_key',
            field=models.CharField(default='operator', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorclick',
            name='button_name',
            field=models.CharField(default='Operator', max_length=100),
        ),
        migrations.AlterField(
            model_name='operatorclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser'),
        ),
    ]
