# Generated by Django 5.2.10 on 2026-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_mashinaclick_options_alter_mikroclick_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorclick',
            name='button_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorclick',
            name='button_name',
            field=models.CharField(max_length=100),
        ),
    ]
