# Generated by Django 5.2.10 on 2026-04-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_operatorclick_button_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriweClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_key', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'UrbanDriwe',
                'verbose_name_plural': '🚗UrbanDriwe bosishlar',
                'ordering': ['-clicked_at'],
                'abstract': False,
            },
        ),
    ]
